### ISSUE TITLE
ccn-lite does not build

### ISSUE THREAD

**Issue by OlegHahm** [cn-uofbasel/ccn-lite#208]
I was trying to build the most recent master version of ccn-lite, but failed.
The [README](https://github.com/cn-uofbasel/ccn-lite/blob/master/doc/README-unix.md) that I should call
```bash
cd $CCNL_HOME
mkdir build && cd build
cmake ../src
make
```
However, there is no Makefile in `build`. Hence, I switched to `src`, but make failed with
```
...
[ 42%] Building C object ccnl-pkt/CMakeFiles/ccnl-pkt.dir/src/ccnl-pkt-switch.c.o
[ 43%] Linking C static library ../lib/libccnl-pkt.a
[ 43%] Built target ccnl-pkt
Scanning dependencies of target ccnl_core_test_uri_to_prefix
[ 44%] Building C object ccnl-core/CMakeFiles/ccnl_core_test_uri_to_prefix.dir/test/ccnl_core_test_uri_to_prefix.c.o
[ 45%] Linking C executable ccnl_core_test_uri_to_prefix
/bin/ld: cannot find -lccnl-nfn
/bin/ld: cannot find -lccnl-unix
collect2: error: ld returned 1 exit status
make[2]: *** [ccnl-core/CMakeFiles/ccnl_core_test_uri_to_prefix.dir/build.make:98: ccnl-core/ccnl_core_test_uri_to_prefix] Error 1
make[1]: *** [CMakeFiles/Makefile2:132: ccnl-core/CMakeFiles/ccnl_core_test_uri_to_prefix.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

**Comment by OlegHahm** [comment]
Trying to build `libccnl-unix` I encountered another problem:
```
/home/oleg/git/ccn-lite/src/ccnl-unix/src/ccnl-unix.c:281:23: error: dereferencing pointer to incomplete type ‘struct tm’
     if (lasthour != tm->tm_hour) {
```
Aside from a bunch of warnings.

**Comment by blacksheeep** [comment]
Can you please give me more details about the OS you are using? And can you add the full console output?

**Comment by cgundogan** [comment]
```sh
cd $CCNL_HOME
mkdir build && cd build
cmake ../src
make
```

just tested on my Arch setup with current master. Tha above steps work for me.

```
cmake --version 
cmake version 3.10.2
```

**Comment by blacksheeep** [comment]
For me it worked on Ubuntu 17.10 and MacOS High Sierra.
That's why I was asking for the OS.

**Comment by OlegHahm** [comment]
I'm still confused how this could work:
```
cd $CCNL_HOME
mkdir build && cd build
cmake ../src
make              
Doxygen build started
-- Configuring done
-- Generating done
-- Build files have been written to: /home/oleg/git/ccn-lite/src
make: *** No targets specified and no makefile found.  Stop.
```

Arch Linux
```
`--> cmake --version                                                                                         [19:05:31][2]
cmake version 3.10.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
.-(~/git/ccn-lite/build)---------------------------------------------------------------------------------(oleg@fireflower)-
`--> gcc --version                                                                                           [19:06:00][0]
gcc (GCC) 7.2.1 20171128
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.-(~/git/ccn-lite/build)---------------------------------------------------------------------------------(oleg@fireflower)-
`--> uname -a                                                                                                [19:06:05][0]
Linux fireflower 4.14.8-1-ARCH #1 SMP PREEMPT Wed Dec 20 21:27:44 UTC 2017 x86_64 GNU/Linux
```
