### ISSUE TITLE
Build cannot find `openssl/sha.h`, while cmake does

### ISSUE THREAD

**Issue by smlng** [cn-uofbasel/ccn-lite#150]
I tried to build CCN-lite on macOS (I know there are issues, but still), but it fails during build due to a missing `openssl/sha.h` header. However, I have openssl installed via _homebrew_ and ran `cmake` successfully as follows:

```
cd ccn-lite/src
mkdir build
cd build
OPENSSL_ROOT_DIR=/usr/local/opt/openssl OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include cmake ../
make
```

as usual there are some warnings about experimental ethernet support on macOS, but it finally fails due to openssl, with:

```
/ccn-lite/src/ccnl-core/include/ccnl-sockunion.h:51:9: warning: ethernet support in FreeBSD and MacOS is work in
      progress and not fully implemented! [-W#pragma-messages]
#pragma message "ethernet support in FreeBSD and MacOS is work in progress \
        ^
/ccn-lite/src/ccnl-core/src/ccnl-prefix.c:37:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

**Comment by smlng** [comment]
and there is a `openssl/sha.h` in `/usr/local/opt/openssl/include/`

**Comment by blacksheeep** [comment]
Can you run:
➜  ~ brew link --force openssl

and try again?

It is working on my Mac, High Sierra 10.13.2.

➜  ~ locate openssl/sha.h
/usr/local/Cellar/openssl/1.0.2l/include/openssl/sha.h
/usr/local/Cellar/openssl/1.0.2m/include/openssl/sha.h
/usr/local/Cellar/openssl@1.1/1.1.0f/include/openssl/sha.h
/usr/local/Cellar/openssl@1.1/1.1.0g/include/openssl/sha.h

**Comment by blacksheeep** [comment]
Can you run:
➜  ~ brew link --force openssl

and try again?

It is working on my Mac, High Sierra 10.13.2.

➜  ~ locate openssl/sha.h
/usr/local/Cellar/openssl/1.0.2l/include/openssl/sha.h
/usr/local/Cellar/openssl/1.0.2m/include/openssl/sha.h
/usr/local/Cellar/openssl@1.1/1.1.0f/include/openssl/sha.h
/usr/local/Cellar/openssl@1.1/1.1.0g/include/openssl/sha.h

**Comment by smlng** [comment]
This is discouraged by `brew` saying:

```
brew link openssl
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

and I also think the problem is somewhat different, because when compiling `ccnl-core/ccnl-prefix.c` the header file `openssl/sha.h` is found. To verify this I added a preprocessor warning directly below the include:

```C
#if !defined(CCNL_RIOT) && !defined(CCNL_ANDROID)
#warning huhu using openssl
#include <openssl/sha.h>
#endif // !defined(CCNL_RIOT) && !defined(CCNL_ANDROID)
```

and during build process I saw:

```cmake
[ 23%] Building C object ccnl-core/CMakeFiles/ccnl-core.dir/src/ccnl-prefix.c.o

/ccn-lite/src/ccnl-core/src/ccnl-prefix.c:37:2: warning: huhu using openssl [-W#warnings]
#warning huhu using openssl
 ^
2 warnings generated.
```

So I think the problem is with compiling `ccnl-unix`, and should be fixed there.

**Comment by blacksheeep** [comment]
So we facing a Bug in the Build system, that do not set up the environment correctly?

I know it was sometimes required to link some pathes for openssl on ubuntu, since they moved it from /usr/local/include to usr/local/<kernelversion>/include. 

For MacOS I never faced such problems. Still, my solution approach to this would be to place openssl/sha.h on a location where the compiler finds it.

**Comment by smlng** [comment]
Hi again,

as pointed out above `cmake` and the compiler do find `openssl` (libs and include) on macOS, too - you only have to specify ` OPENSSL_ROOT_DIR=/usr/local/opt/openssl` when running `cmake`. Whats interesting is that `ccnl-core` is the only target that finds `openssl` while all others fail, as reported. I also found that after running `OPENSSL_ROOT_DIR=/usr/local/opt/openssl cmake ../` in my build folder I used `find` to check all `flags.make` files generated per sub target, it gives the following output:

```
$ find . -name flags.make -exec grep C_FLAGS {} +
./ccnl-core/CMakeFiles/ccnl-core.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include  
./ccnl-fwd/CMakeFiles/ccnl-fwd.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-nfn/CMakeFiles/ccnl-nfn.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-pkt/CMakeFiles/ccnl-pkt.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-pkt-compression/CMakeFiles/ccnl-pkt-compression.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-relay/CMakeFiles/ccn-lite-relay.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-unix/CMakeFiles/ccnl-unix.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-ccnb2xml.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-cryptoserver.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-ctrl.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-fetch.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-mkC.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-mkI.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-peek.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-pktdump.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-produce.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-rpc.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-simplenfn.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-valid.dir/flags.make:C_FLAGS =  -Wextra -Wall -Werror -std=c99 -g -pedantic
``` 

as you see only for `ccnl-core` they are different and have the right include set, which is why `ccnl-prefix.c` finds `openssl/sha.h` while all other do not.

I found a work around, when running `cmake` with as follows:

```
OPENSSL_ROOT_DIR=/usr/local/opt/openssl cmake -DCMAKE_C_FLAGS="-I/usr/local/opt/openssl/include" ../
```

after that build succeeds and `flags.make` files are as follows:

```
find . -name flags.make -exec grep C_FLAGS {} +
./ccnl-core/CMakeFiles/ccnl-core.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include  
./ccnl-fwd/CMakeFiles/ccnl-fwd.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-nfn/CMakeFiles/ccnl-nfn.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-pkt/CMakeFiles/ccnl-pkt.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-pkt-compression/CMakeFiles/ccnl-pkt-compression.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-relay/CMakeFiles/ccn-lite-relay.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-unix/CMakeFiles/ccnl-unix.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-ccnb2xml.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-cryptoserver.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-ctrl.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-fetch.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-mkC.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-mkI.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-peek.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-pktdump.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-produce.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-rpc.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-simplenfn.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic  
./ccnl-utils/CMakeFiles/ccn-lite-valid.dir/flags.make:C_FLAGS = -I/usr/local/opt/openssl/include -Wextra -Wall -Werror -std=c99 -g -pedantic 
```

So to conclude, somehow cmake overwrites `C_FLAGS` for `ccnl-core` but not for all other targets.

**Comment by blacksheeep** [comment]
can you verify if adding this block to line 8 of src/CMakeLists.txt fixes the problem?
`
#opensll
find_package(OpenSSL)
if(OpenSSL_FOUND)
    include_directories(${OPENSSL_INCLUDE_DIRS})
endif()
`

**Comment by smlng** [comment]
@blacksheeep see #155
