### PR TITLE
arduino adapter: missing include

### LINKED ISSUE #106: 'ssize_t' does not name a type in ccnl-core.h:148:5 - CCNLite-Arduino
src/../../ccnl-core.h:148:5 error: 'ssize_t' doesn not name a type
ssize_t datalen;
I have included ethernet libraries successfully and upon running "make all upload" gives this error.
Can anyone tell me where i am going wrong here?

### PR DESCRIPTION
**Pull request by OlegHahm**
Hopefully fixes #106.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Disclaimer: untested since I don't know how to build for Arduino.

**Comment by blacksheeep** [comment]
I get build errors on linux, x86 using this patch: 
ccnl-core.c:855:17: error: expected ‘)’ before ‘PRIi32’

**Comment by OlegHahm** [comment]
That's very interesting. I will investigate.

**Comment by OlegHahm** [comment]
Apparently, the avr-gcc toolchain doesn't contain a type definition for `ssize_t`. I changed the PR accordingly.

**Comment by OlegHahm** [comment]
There were some missing defines for Arduino.

**Comment by blacksheeep** [comment]
I have still some errors:
ccnl-core.c:855:17: error: expected ‘)’ before ‘PRIi32’
ccnl-core-fwd.c:209:5: error: expected ‘)’ before ‘PRIi32’

**Comment by OlegHahm** [comment]
Strange since I defined this macro in https://github.com/cn-uofbasel/ccn-lite/pull/107/commits/b7ad12d56a57e23d64bccc5295a972367256f20a

**Comment by OlegHahm** [comment]
@blacksheeep. can you paste the full compiler output and your toolchain version?

**Comment by blacksheeep** [comment]
Here you go:  

make clean USE_NFN=1 USE_NACK=1
*** Configuring for Linux ***
*** With NFN ***
*** With NFN_NACK ***
make[1]: Entering directory `/home/travis/build/cn-uofbasel/ccn-lite/src'
rm -rf *~ *.o  ccn-lite-simu ccn-lite-relay  ccn-nfn-relay ccn-lite-relay-nack ccn-nfn-relay-nack ccn-lite-lnxkernel ccn-lite-simu ccn-nfn-relay ccn-lite-relay-nack ccn-nfn-relay-nack ccn-lite-repo256
rm -rf .ccn-lite-lnxkernel* *.ko *.mod.c *.mod.o .tmp_versions modules.order Module.symvers
rm -rf ccn-lite-omnet.tgz
rm -rf ../bin
make -C util clean
*** With NFN ***
make[2]: Entering directory `/home/travis/build/cn-uofbasel/ccn-lite/src/util'
rm -rf *~ ccn-lite-ccnb2xml ccn-lite-cryptoserver ccn-lite-ctrl ccn-lite-fetch ccn-lite-mkC ccn-lite-mkI ccn-lite-mkF ccn-lite-peek ccn-lite-pktdump ccn-lite-produce ccn-lite-rpc ccn-lite-simplenfn ccn-lite-valid 
rm -rf ../../bin
make[2]: Leaving directory `/home/travis/build/cn-uofbasel/ccn-lite/src/util'
make[1]: Leaving directory `/home/travis/build/cn-uofbasel/ccn-lite/src'
$ make -j32 -k ccn-lite-relay
*** Configuring for Linux ***
make[1]: Entering directory `/home/travis/build/cn-uofbasel/ccn-lite/src'
gcc -o ccn-lite-relay -Wall -Werror -std=c99 -g -pedantic -O0 -D_XOPEN_SOURCE=500 -D_XOPEN_SOURCE_EXTENDED -Dlinux ccn-lite-relay.c -lcrypto -lrt
In file included from ccn-lite-relay.c:76:0:
ccnl-core.c: In function ‘ccnl_content_serve_pending’:
ccnl-core.c:855:17: error: expected ‘)’ before ‘PRIi32’
ccnl-core.c:855:17: error: format ‘%s’ expects a matching ‘char *’ argument [-Werror=format]
ccnl-core.c:855:17: error: format ‘%s’ expects a matching ‘char *’ argument [-Werror=format]
ccnl-core.c:855:17: error: spurious trailing ‘%’ in format [-Werror=format]
In file included from ccnl-core.c:1055:0,
                 from ccn-lite-relay.c:76:
ccnl-core-fwd.c: In function ‘ccnl_fwd_handleInterest’:
ccnl-core-fwd.c:209:5: error: expected ‘)’ before ‘PRIi32’
ccnl-core-fwd.c:209:5: error: format ‘%s’ expects a matching ‘char *’ argument [-Werror=format]
ccnl-core-fwd.c:209:5: error: format ‘%s’ expects a matching ‘char *’ argument [-Werror=format]
ccnl-core-fwd.c:209:5: error: spurious trailing ‘%’ in format [-Werror=format]
cc1: all warnings being treated as errors
make[1]: *** [ccn-lite-relay] Error 1
make[1]: Leaving directory `/home/travis/build/cn-uofbasel/ccn-lite/src'
make: *** [bt-relay-nothing] Error 1

**Comment by OlegHahm** [comment]
Ah, okay, this has nothing to do with Arduino (or this PR). This problem has been introduced in https://github.com/cn-uofbasel/ccn-lite/pull/104 by @smlng.
