### PR TITLE
updating glibc feature test macros

### PR DESCRIPTION
**Pull request by OlegHahm**
In current glibc versions _BSD_SOURCE and _SVID_SOURCE are marked and create compiler warnings, _DEFAULT_SOURCE can be used instead.

Current master won't compile with gcc 5.2.0 and glibc 2.22, because of
```
In file included from /usr/include/fcntl.h:25:0,
                 from ccnl-common.c:41,
                 from ccn-lite-ccnb2xml.c:31:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
```

### CODE REVIEW

**Comment by blacksheeep** [comment]
I applied the patch, thanks
